org.gradle.jvmargs=-Xms256m -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.caching=false

ABI_FILTERS=arm64-v8a

takDebugKeyAlias=key0
takDebugKeyFile=key.jks
takDebugKeyFilePassword=android
takDebugKeyPassword=android
takReleaseKeyAlias=key0
takReleaseKeyFile=key.jks
takReleaseKeyFilePassword=android
takReleaseKeyPassword=android
