package com.atakmap.android.twcoord.address.geo;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.junit.Test;

/**
 * Feature 006 T008 — the dependency-free WKB MultiPolygon parser. Hand-built WKB blobs cover the
 * shape/endianness/malformed cases; the fixture {@code townships-fixture.sqlite} provides a real
 * {@code geometry_wkb} blob (台中市西區) to prove the parser handles authentic generator output and
 * resolves a known interior point.
 */
public class WkbMultiPolygonParserTest {

  // ---- hand-built WKB helpers (little-endian, OGC 2D) ----

  private static byte[] wkbPolygon(double[][] rings) {
    // rings[0] = exterior; rings[1..] = holes. Each ring is [x0,y0,x1,y1,...].
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    writeByte(out, 1); // LE
    writeU32(out, 3); // Polygon
    writeU32(out, rings.length);
    for (double[] ring : rings) {
      int npts = ring.length / 2;
      writeU32(out, npts);
      for (int i = 0; i < ring.length; i++) {
        writeF64(out, ring[i]);
      }
    }
    return out.toByteArray();
  }

  private static byte[] wkbMultiPolygon(double[][][] polys) {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    writeByte(out, 1); // LE
    writeU32(out, 6); // MultiPolygon
    writeU32(out, polys.length);
    for (double[][] rings : polys) {
      byte[] poly = wkbPolygon(rings);
      out.write(poly, 0, poly.length);
    }
    return out.toByteArray();
  }

  private static void writeByte(ByteArrayOutputStream o, int b) {
    o.write(b & 0xFF);
  }

  private static void writeU32(ByteArrayOutputStream o, int v) {
    ByteBuffer bb = ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN);
    bb.putInt(v);
    o.write(bb.array(), 0, 4);
  }

  private static void writeF64(ByteArrayOutputStream o, double v) {
    ByteBuffer bb = ByteBuffer.allocate(8).order(ByteOrder.LITTLE_ENDIAN);
    bb.putDouble(v);
    o.write(bb.array(), 0, 8);
  }

  private static final double[] SQUARE = {0, 0, 10, 0, 10, 10, 0, 10, 0, 0};

  // ---- shape parsing ----

  @Test
  public void parsesType6MultiPolygonSinglePolygon() {
    byte[] wkb = wkbMultiPolygon(new double[][][] {{SQUARE}});
    BoundaryGeometry g = WkbMultiPolygonParser.parseOrNull(wkb);
    assertThat(g).isNotNull();
    assertThat(g.polygonCount()).isEqualTo(1);
    assertThat(g.covers(5, 5)).isTrue();
    assertThat(g.covers(50, 50)).isFalse();
  }

  @Test
  public void parsesType3Polygon() {
    byte[] wkb = wkbPolygon(new double[][] {SQUARE});
    BoundaryGeometry g = WkbMultiPolygonParser.parseOrNull(wkb);
    assertThat(g).isNotNull();
    assertThat(g.covers(5, 5)).isTrue();
  }

  @Test
  public void respectsHoles() {
    double[] hole = {4, 4, 6, 4, 6, 6, 4, 6, 4, 4};
    byte[] wkb = wkbPolygon(new double[][] {SQUARE, hole});
    BoundaryGeometry g = WkbMultiPolygonParser.parseOrNull(wkb);
    assertThat(g).isNotNull();
    assertThat(g.covers(5, 5)).isFalse(); // in the hole
    assertThat(g.covers(1, 1)).isTrue(); // outside the hole
  }

  // ---- malformed → null (never throw) ----

  @Test
  public void truncatedBlobReturnsNull() {
    byte[] full = wkbMultiPolygon(new double[][][] {{SQUARE}});
    byte[] cut = new byte[full.length - 20];
    System.arraycopy(full, 0, cut, 0, cut.length);
    assertThat(WkbMultiPolygonParser.parseOrNull(cut)).isNull();
  }

  @Test
  public void bigEndianByteOrderReturnsNull() {
    byte[] wkb = wkbMultiPolygon(new double[][][] {{SQUARE}});
    wkb[0] = 0; // flip to big-endian marker
    assertThat(WkbMultiPolygonParser.parseOrNull(wkb)).isNull();
  }

  @Test
  public void unexpectedTypeCodeReturnsNull() {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    writeByte(out, 1);
    writeU32(out, 1); // Point — unsupported
    writeF64(out, 1.0);
    writeF64(out, 2.0);
    assertThat(WkbMultiPolygonParser.parseOrNull(out.toByteArray())).isNull();
  }

  @Test
  public void nullAndEmptyReturnNull() {
    assertThat(WkbMultiPolygonParser.parseOrNull(null)).isNull();
    assertThat(WkbMultiPolygonParser.parseOrNull(new byte[0])).isNull();
    assertThat(WkbMultiPolygonParser.parseOrNull(new byte[] {1, 6})).isNull();
  }

  // ---- real generator blob from the fixture ----

  @Test
  public void parsesRealTownshipBlobAndCoversInteriorPoint() throws Exception {
    Path fixture = Paths.get("src/test/resources/fixtures/townships-fixture.sqlite");
    if (!Files.exists(fixture)) {
      // Fixture is regenerated by scripts/build_test_fixtures.py; skip if absent in this checkout.
      return;
    }
    Class.forName("org.sqlite.JDBC");
    try (Connection conn =
        DriverManager.getConnection("jdbc:sqlite:" + fixture.toAbsolutePath())) {
      // 台中市西區 contains 台中車站 (24.1417, 120.6736).
      byte[] wkb = null;
      try (PreparedStatement ps =
          conn.prepareStatement(
              "SELECT geometry_wkb FROM townships WHERE name_zh='西區' AND county_zh='台中市'")) {
        try (ResultSet rs = ps.executeQuery()) {
          if (rs.next()) wkb = rs.getBytes(1);
        }
      }
      assertThat(wkb).isNotNull();
      BoundaryGeometry g = WkbMultiPolygonParser.parseOrNull(wkb);
      assertThat(g).isNotNull();
      assertThat(g.vertexCount()).isGreaterThan(3);
      assertThat(g.covers(24.1417, 120.6736)).isTrue(); // 台中車站 inside 西區
      assertThat(g.covers(23.0, 120.0)).isFalse(); // far away
    }
  }
}
